### ISSUE TITLE
New Feature Request: Barns and Coops

### ISSUE THREAD

**Issue by Mikesnorth** [OtherBuckets/StardewNewsFeed#6]
User Request: https://www.nexusmods.com/stardewvalley/mods/3206?tab=posts
It's a really good idea to include barns and coops in the scanning.

## Details
At the start of the day, barns and coops should all be scanned for items that can be harvested, and animals that can be tended to (milk cows and goats, sheer sheep).

## Items for discussion
Do we display a notification per barn/coop, or do we aggregate and display 1 notification that encompasses all barns, and 1 that encompasses all coops?
My current thinking is that it would be an aggregation by default, but have a configuration option that allows users to change it to a notification per building.

**Comment by ingramam** [comment]
I'll take this one.

**Comment by ingramam** [comment]
Created PR: #25
